[tasks.build]
description = "build all binaries"
run = "go build -o bin/backend cmd/backend/main.go"

[tasks.gen]
description = "generate genereated code"
run = ["swag init -g cmd/backend/main.go", "go generate ./..."]

[tasks.fmt]
description = "fmt files"
run = ["swag fmt", "go fmt ./..."]
