version: "3"

env:
  PROJECT_ROOT:
    sh: pwd
  SQLC_HELPER:
    sh: python -c "import os; print(os.path.join(os.getcwd(), \"tools\", \"sqlc_helper.py\"), end=\"\")"
  GOENUM:
    sh: python -c "import os; print(os.path.join(os.getcwd(), \"tools\", \"goenum.py\"))"

tasks:
  generate:
    cmds:
      - go tool github.com/swaggo/swag/cmd/swag init -g cmd/backend/main.go
      - go generate ./...
      # - go tool github.com/go-swagger/go-swagger/cmd/swagger generate cli
  build:
    deps: [generate]
    cmds:
      - go build -ldflags="-w -s" -o bin/backend cmd/backend/main.go
  lint:
    cmds:
      - golangci-lint run
  fmt:
    cmds:
      - swag fmt
      - go fmt ./...
  run:
    deps: [build]
    cmds:
      - bin/backend --config config/backend.yml
