version: "3"

env:
  PROJECT_ROOT:
    sh: pwd
  SQLC_HELPER: "{{.PROJECT_ROOT}}/tools/sqlc_helper.sh"
tasks:
  generate:
    cmds:
      - swag init -g cmd/backend/main.go
      - go generate ./...
  build:
    deps: [generate]
    cmds:
      - go build -ldflags="-w -s" -o bin/backend cmd/backend/main.go
  lint:
    cmds:
      - golangci-lint run
  fmt:
    cmds:
      - swag fmt
      - go fmt ./...
