version: "3"

tasks:
  deps:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/abice/go-enum@latest
  generate:
    cmds:
      - swag init -g cmd/backend/main.go
      - go generate ./...
  build:
    cmds:
      - go build -o bin/backend cmd/backend/main.go
  lint:
    cmds:
      - golangci-lint run
  fmt:
    cmds:
      - swag fmt
      - go fmt ./...
