version: "3"

vars:

env:
  PROJECT_ROOT:
    sh: pwd
  SQLC_HELPER:
    sh: python -c "import os; print(os.path.join(os.getcwd(), \"tools\", \"sqlc_helper.py\"), end=\"\")"

tasks:
  generate:
    cmds:
      - go tool github.com/swaggo/swag/cmd/swag init -g cmd/backend/main.go
      - go generate ./...
  build:
    deps: [generate]
    cmds:
      - go build -ldflags="-w -s" -o bin/backend cmd/backend/main.go
  lint:
    cmds:
      - golangci-lint run
  fmt:
    cmds:
      - swag fmt
      - go fmt ./...
