// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initUsers = `-- name: InitUsers :exec
CREATE TABLE IF NOT EXISTS users (
    id varchar(36) PRIMARY KEY,
    role int NOT NULL,
    login varchar(36) NOT NULL UNIQUE,
    hash text NOT NULL,
    UNIQUE KEY unique_username (login)
)
`

func (q *Queries) InitUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initUsers)
	return err
}
