// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initUsers = `-- name: InitUsers :exec
CREATE TABLE IF NOT EXISTS users (
    id varchar(36) PRIMARY KEY,
    role int NOT NULL,
    login text NOT NULL UNIQUE,
    hash text NOT NULL
)
`

func (q *Queries) InitUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initUsers)
	return err
}
