-- Generated by TestGenerateLegacyDump (go test ./internal/backend/functest -update).
-- A snapshot of a database written by the GORM-era code. Do not edit by hand.

CREATE TABLE `favorite_lists` (`id` text NOT NULL,`list_type` integer NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`id`));
CREATE TABLE `favorite_members` (`id` text NOT NULL,`user_id` text NOT NULL,`favorite_list_id` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,`member_type` integer NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `fk_favorite_members_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),CONSTRAINT `fk_favorite_lists_members` FOREIGN KEY (`favorite_list_id`) REFERENCES `favorite_lists`(`id`));
CREATE TABLE `favorite_products` (`id` text NOT NULL,`product_id` text NOT NULL,`favorite_list_id` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `fk_favorite_products_product` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`),CONSTRAINT `fk_favorite_lists_products` FOREIGN KEY (`favorite_list_id`) REFERENCES `favorite_lists`(`id`));
CREATE TABLE `product_categories` (`id` text,`name` text,PRIMARY KEY (`id`));
CREATE TABLE `product_forms` (`product_id` text,`id` text,`name` text,PRIMARY KEY (`id`),CONSTRAINT `fk_products_forms` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`));
CREATE TABLE `product_list_members` (`id` text NOT NULL,`user_id` text NOT NULL,`list_id` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,`member_type` integer NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `fk_product_list_members_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),CONSTRAINT `fk_product_lists_members` FOREIGN KEY (`list_id`) REFERENCES `product_lists`(`id`) ON DELETE CASCADE);
CREATE TABLE `product_list_states` (`id` text NOT NULL,`product_id` text NOT NULL,`list_id` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,`index` integer NOT NULL,`count` integer,`form_idx` integer,`status` integer NOT NULL,`replacement_count` integer,`replacement_form_idx` integer,`replacement_product_id` text,PRIMARY KEY (`id`),CONSTRAINT `fk_product_list_states_product` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`),CONSTRAINT `fk_product_list_states_replacement_product` FOREIGN KEY (`replacement_product_id`) REFERENCES `products`(`id`),CONSTRAINT `fk_product_lists_states` FOREIGN KEY (`list_id`) REFERENCES `product_lists`(`id`));
CREATE TABLE `product_lists` (`id` text NOT NULL,`status` integer NOT NULL,`updated_at` datetime NOT NULL,`created_at` datetime NOT NULL,`title` text,PRIMARY KEY (`id`));
CREATE TABLE `products` (`id` text,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,`name` text NOT NULL,`category_id` text,PRIMARY KEY (`id`),CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `product_categories`(`id`));
CREATE TABLE shop_map_categories (
    map_id varchar(36) NOT NULL,
    number integer NOT NULL,
    category varchar(255) NOT NULL,
    PRIMARY KEY (map_id, number),
    FOREIGN KEY(map_id) REFERENCES shop_maps(id)
);
CREATE TABLE shop_map_viewers (
    map_id varchar(36) NOT NULL,
    user_id varchar(36) NOT NULL,
    FOREIGN KEY (map_id) REFERENCES shop_maps(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE shop_maps (
    id varchar(36) PRIMARY KEY,
    owner_id varchar(36) NOT NULL,
    title varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
CREATE TABLE "users"  (id varchar(36) PRIMARY KEY,`role` integer,`login` text,`hash` text);
CREATE UNIQUE INDEX `idx_list_user` ON `product_list_members`(`user_id`,`list_id`);
CREATE UNIQUE INDEX `idx_unique_product` ON `favorite_products`(`product_id`,`favorite_list_id`);
CREATE UNIQUE INDEX `idx_users_login` ON `users`(`login`);

-- favorite_lists
INSERT INTO "favorite_lists" ("id", "list_type", "created_at", "updated_at") VALUES ('54ae4a9b-9a4c-4c17-a11d-02edf93afa63', 1, '2026-08-09 13:30:31.694147439+03:00', '2026-08-09 13:30:31.778209016+03:00');
INSERT INTO "favorite_lists" ("id", "list_type", "created_at", "updated_at") VALUES ('e5822831-b36b-4f71-839c-d54f3147474e', 1, '2026-08-09 13:30:31.732596907+03:00', '2026-08-09 13:30:31.778610936+03:00');
INSERT INTO "favorite_lists" ("id", "list_type", "created_at", "updated_at") VALUES ('0846eedb-5503-46fc-a0b1-3c66643bbed4', 1, '2026-08-09 13:30:31.771024146+03:00', '2026-08-09 13:30:31.771024176+03:00');

-- favorite_members
INSERT INTO "favorite_members" ("id", "user_id", "favorite_list_id", "created_at", "updated_at", "member_type") VALUES ('17b38308-50a2-4ca4-94a1-ffb203f12a01', '1cc330b8-49be-4438-9282-f82f0238567f', '0846eedb-5503-46fc-a0b1-3c66643bbed4', '2026-08-09 13:30:31.771024046+03:00', '2026-08-09 13:30:31.771024086+03:00', 1);
INSERT INTO "favorite_members" ("id", "user_id", "favorite_list_id", "created_at", "updated_at", "member_type") VALUES ('784cffb0-d923-45db-9a16-8557882a8322', 'eaf6eca9-91b4-478f-a0f5-375d278a6eee', '54ae4a9b-9a4c-4c17-a11d-02edf93afa63', '2026-08-09 13:30:31.694147379+03:00', '2026-08-09 13:30:31.694147409+03:00', 1);
INSERT INTO "favorite_members" ("id", "user_id", "favorite_list_id", "created_at", "updated_at", "member_type") VALUES ('531cab9a-a953-4879-9674-5f0a6d6f705e', '91a3009e-706c-42e9-a857-ffdd39c20031', 'e5822831-b36b-4f71-839c-d54f3147474e', '2026-08-09 13:30:31.732596847+03:00', '2026-08-09 13:30:31.732596877+03:00', 1);

-- favorite_products
INSERT INTO "favorite_products" ("id", "product_id", "favorite_list_id", "created_at", "updated_at") VALUES ('db0c1f47-5800-4ab2-a3db-58fc851514c3', '54e6b64b-9815-4617-9bec-b5f1cd4e4d05', '54ae4a9b-9a4c-4c17-a11d-02edf93afa63', '2026-08-09 13:30:31.777997617+03:00', '2026-08-09 13:30:31.777997647+03:00');
INSERT INTO "favorite_products" ("id", "product_id", "favorite_list_id", "created_at", "updated_at") VALUES ('f6690742-1ba2-453b-9487-996c3208d653', '336afd11-4a5f-4d91-8be3-b17a0eee341f', '54ae4a9b-9a4c-4c17-a11d-02edf93afa63', '2026-08-09 13:30:31.777997737+03:00', '2026-08-09 13:30:31.777997767+03:00');
INSERT INTO "favorite_products" ("id", "product_id", "favorite_list_id", "created_at", "updated_at") VALUES ('20365bdf-9908-4527-b230-5ea8f2368806', 'f3dcc407-4736-4f00-b684-801badd5b089', 'e5822831-b36b-4f71-839c-d54f3147474e', '2026-08-09 13:30:31.778456536+03:00', '2026-08-09 13:30:31.778456566+03:00');

-- product_categories
INSERT INTO "product_categories" ("id", "name") VALUES ('c64fe902-de06-471d-ac14-c1b97c1b058e', 'dairy');
INSERT INTO "product_categories" ("id", "name") VALUES ('6e06a3c5-f735-4330-82ec-d3f63121acad', 'bakery');
INSERT INTO "product_categories" ("id", "name") VALUES ('00436ae0-5dfa-4416-8060-860c9ed94845', '');
INSERT INTO "product_categories" ("id", "name") VALUES ('65422efa-594d-4e1b-9d92-7d3efe5a8498', '');

-- product_forms
INSERT INTO "product_forms" ("product_id", "id", "name") VALUES ('54e6b64b-9815-4617-9bec-b5f1cd4e4d05', '39727b9c-87e5-4644-a4fc-e6994812c73d', 'bottle');
INSERT INTO "product_forms" ("product_id", "id", "name") VALUES ('54e6b64b-9815-4617-9bec-b5f1cd4e4d05', '551fb359-5469-48f7-8123-be59efeaa44c', 'carton');
INSERT INTO "product_forms" ("product_id", "id", "name") VALUES ('336afd11-4a5f-4d91-8be3-b17a0eee341f', '2ae8db96-e0a0-44de-bf17-18d36047346c', 'block');

-- product_list_members
INSERT INTO "product_list_members" ("id", "user_id", "list_id", "created_at", "updated_at", "member_type") VALUES ('4fe1a94a-99e5-4704-988a-7195768f0e11', 'eaf6eca9-91b4-478f-a0f5-375d278a6eee', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.771710015+03:00', '2026-08-09 13:30:31.771710055+03:00', 1);
INSERT INTO "product_list_members" ("id", "user_id", "list_id", "created_at", "updated_at", "member_type") VALUES ('545506c2-d836-44b4-b546-94139b946f6f', '91a3009e-706c-42e9-a857-ffdd39c20031', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.772518544+03:00', '2026-08-09 13:30:31.772518584+03:00', 3);
INSERT INTO "product_list_members" ("id", "user_id", "list_id", "created_at", "updated_at", "member_type") VALUES ('545a494b-701c-44c2-93ec-22fa3006e7f8', '1cc330b8-49be-4438-9282-f82f0238567f', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.773173703+03:00', '2026-08-09 13:30:31.773173763+03:00', 5);
INSERT INTO "product_list_members" ("id", "user_id", "list_id", "created_at", "updated_at", "member_type") VALUES ('b737a3c4-a745-40da-82ee-ce756ff2a707', '91a3009e-706c-42e9-a857-ffdd39c20031', 'c5ff01fe-5d15-4a68-8573-7ac3f880974d', '2026-08-09 13:30:31.777649147+03:00', '2026-08-09 13:30:31.777649187+03:00', 1);

-- product_list_states
INSERT INTO "product_list_states" ("id", "product_id", "list_id", "created_at", "updated_at", "index", "count", "form_idx", "status", "replacement_count", "replacement_form_idx", "replacement_product_id") VALUES ('a8a53df9-0825-4646-80ae-6e16b552c636', '54e6b64b-9815-4617-9bec-b5f1cd4e4d05', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.773668712+03:00', '2026-08-09 13:30:31.773668752+03:00', 1, 2, 1, 3, NULL, NULL, NULL);
INSERT INTO "product_list_states" ("id", "product_id", "list_id", "created_at", "updated_at", "index", "count", "form_idx", "status", "replacement_count", "replacement_form_idx", "replacement_product_id") VALUES ('89b622c2-1080-49f4-b534-badc37f8f26e', 'f3dcc407-4736-4f00-b684-801badd5b089', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.774281952+03:00', '2026-08-09 13:30:31.774281982+03:00', 2, NULL, NULL, 1, NULL, NULL, NULL);
INSERT INTO "product_list_states" ("id", "product_id", "list_id", "created_at", "updated_at", "index", "count", "form_idx", "status", "replacement_count", "replacement_form_idx", "replacement_product_id") VALUES ('0966b123-9130-4387-9012-b00190e0843a', '336afd11-4a5f-4d91-8be3-b17a0eee341f', 'b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', '2026-08-09 13:30:31.774882011+03:00', '2026-08-09 13:30:31.774882051+03:00', 0, NULL, NULL, 4, 1, NULL, 'e4e06c64-c33d-45b1-952d-7d276335dc78');

-- product_lists
INSERT INTO "product_lists" ("id", "status", "updated_at", "created_at", "title") VALUES ('b63f35f4-8fe5-4322-9bb6-d59d9ae6e094', 1, '2026-08-09 13:30:31.776613388+03:00', '2026-08-09 13:30:31.771710435+03:00', 'weekly groceries');
INSERT INTO "product_lists" ("id", "status", "updated_at", "created_at", "title") VALUES ('c5ff01fe-5d15-4a68-8573-7ac3f880974d', 1, '2026-08-09 13:30:31.777651217+03:00', '2026-08-09 13:30:31.777651177+03:00', 'hardware');

-- products
INSERT INTO "products" ("id", "created_at", "updated_at", "name", "category_id") VALUES ('54e6b64b-9815-4617-9bec-b5f1cd4e4d05', '2026-08-09 13:30:31.771124306+03:00', '2026-08-09 13:30:31.771124336+03:00', 'milk', 'c64fe902-de06-471d-ac14-c1b97c1b058e');
INSERT INTO "products" ("id", "created_at", "updated_at", "name", "category_id") VALUES ('f3dcc407-4736-4f00-b684-801badd5b089', '2026-08-09 13:30:31.771373016+03:00', '2026-08-09 13:30:31.771373046+03:00', 'bread', '6e06a3c5-f735-4330-82ec-d3f63121acad');
INSERT INTO "products" ("id", "created_at", "updated_at", "name", "category_id") VALUES ('336afd11-4a5f-4d91-8be3-b17a0eee341f', '2026-08-09 13:30:31.771484945+03:00', '2026-08-09 13:30:31.771484975+03:00', 'cheese', 'c64fe902-de06-471d-ac14-c1b97c1b058e');
INSERT INTO "products" ("id", "created_at", "updated_at", "name", "category_id") VALUES ('e4e06c64-c33d-45b1-952d-7d276335dc78', '2026-08-09 13:30:31.771614895+03:00', '2026-08-09 13:30:31.771614935+03:00', 'oat milk', 'c64fe902-de06-471d-ac14-c1b97c1b058e');

-- shop_map_categories
INSERT INTO "shop_map_categories" ("map_id", "number", "category") VALUES ('6941c695-24de-4a58-aa40-8c0d516d1e23', 0, 'dairy');
INSERT INTO "shop_map_categories" ("map_id", "number", "category") VALUES ('6941c695-24de-4a58-aa40-8c0d516d1e23', 1, 'bakery');
INSERT INTO "shop_map_categories" ("map_id", "number", "category") VALUES ('6941c695-24de-4a58-aa40-8c0d516d1e23', 2, 'produce');
INSERT INTO "shop_map_categories" ("map_id", "number", "category") VALUES ('0c3db8b1-a733-41b9-84f4-c6ee9785ad3f', 0, 'produce');

-- shop_map_viewers
INSERT INTO "shop_map_viewers" ("map_id", "user_id") VALUES ('6941c695-24de-4a58-aa40-8c0d516d1e23', '91a3009e-706c-42e9-a857-ffdd39c20031');

-- shop_maps
INSERT INTO "shop_maps" ("id", "owner_id", "title", "created_at", "updated_at") VALUES ('6941c695-24de-4a58-aa40-8c0d516d1e23', 'eaf6eca9-91b4-478f-a0f5-375d278a6eee', 'corner shop', '2026-08-09 13:30:31.778672596+03:00', '2026-08-09 13:30:31.778672626+03:00');
INSERT INTO "shop_maps" ("id", "owner_id", "title", "created_at", "updated_at") VALUES ('0c3db8b1-a733-41b9-84f4-c6ee9785ad3f', '91a3009e-706c-42e9-a857-ffdd39c20031', 'big store', '2026-08-09 13:30:31.778792646+03:00', '2026-08-09 13:30:31.778792676+03:00');

-- users
INSERT INTO "users" ("id", "role", "login", "hash") VALUES ('eaf6eca9-91b4-478f-a0f5-375d278a6eee', 2, 'alice', '$2a$10$h9KhLLrUe.dG0ytidoPHbe5ebBM7BTdzlUyyR0NzUu.OunXDnE0V6');
INSERT INTO "users" ("id", "role", "login", "hash") VALUES ('91a3009e-706c-42e9-a857-ffdd39c20031', 2, 'bob', '$2a$10$VAK5Z4oxh5qqK5lruWoUGurIAw/wR3fHDDZjslhBi7a1AsS7XFi/W');
INSERT INTO "users" ("id", "role", "login", "hash") VALUES ('1cc330b8-49be-4438-9282-f82f0238567f', 2, 'carol', '$2a$10$Ti3BiwEPoD1TsFo.4rYmde0BEdrMkrIxqP3.T4/RsBWCDC.ttSLXy');

