// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"time"
)

type FavoriteList struct {
	ID        string
	ListType  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FavoriteMember struct {
	ID             string
	UserID         string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MemberType     int64
}

type FavoriteProduct struct {
	ID             string
	ProductID      string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
