// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"database/sql"
	"time"
)

type FavoriteList struct {
	ID        string
	ListType  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FavoriteMember struct {
	ID             string
	UserID         string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MemberType     int32
}

type FavoriteProduct struct {
	ID             string
	ProductID      string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Product struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	CategoryID sql.NullString
}

type ProductCategory struct {
	ID   string
	Name string
}

type ProductForm struct {
	ID        string
	ProductID string
	Name      string
}
