// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlgen

import (
	"context"
	"strings"
	"time"
)

const deleteMembersByListID = `-- name: DeleteMembersByListID :exec
DELETE FROM
    favorite_members
WHERE
    favorite_list_id = ?
`

func (q *Queries) DeleteMembersByListID(ctx context.Context, favoriteListID string) error {
	_, err := q.db.ExecContext(ctx, deleteMembersByListID, favoriteListID)
	return err
}

const deleteProductsByListID = `-- name: DeleteProductsByListID :exec
DELETE FROM
    favorite_products
WHERE
    favorite_list_id = ?
`

func (q *Queries) DeleteProductsByListID(ctx context.Context, favoriteListID string) error {
	_, err := q.db.ExecContext(ctx, deleteProductsByListID, favoriteListID)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT
    id, list_type, created_at, updated_at
FROM
    favorite_lists
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetListByID(ctx context.Context, id string) (FavoriteList, error) {
	row := q.db.QueryRowContext(ctx, getListByID, id)
	var i FavoriteList
	err := row.Scan(
		&i.ID,
		&i.ListType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListIDListByUserID = `-- name: GetListIDListByUserID :many
SELECT
    favorite_list_id
FROM
    favorite_members
WHERE
    user_id = ?
`

func (q *Queries) GetListIDListByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getListIDListByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var favorite_list_id string
		if err := rows.Scan(&favorite_list_id); err != nil {
			return nil, err
		}
		items = append(items, favorite_list_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByIDList = `-- name: GetListsByIDList :many
SELECT
    id, list_type, created_at, updated_at
FROM
    favorite_lists
WHERE
    id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetListsByIDList(ctx context.Context, ids []string) ([]FavoriteList, error) {
	query := getListsByIDList
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteList
	for rows.Next() {
		var i FavoriteList
		if err := rows.Scan(
			&i.ID,
			&i.ListType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersByListIDList = `-- name: GetMembersByListIDList :many
SELECT
    id, user_id, favorite_list_id, created_at, updated_at, member_type
FROM
    favorite_members
WHERE
    favorite_list_id IN (/*SLICE:list_ids*/?)
ORDER BY
    rowid
`

func (q *Queries) GetMembersByListIDList(ctx context.Context, listIds []string) ([]FavoriteMember, error) {
	query := getMembersByListIDList
	var queryParams []interface{}
	if len(listIds) > 0 {
		for _, v := range listIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:list_ids*/?", strings.Repeat(",?", len(listIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:list_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteMember
	for rows.Next() {
		var i FavoriteMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FavoriteListID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByListIDList = `-- name: GetProductsByListIDList :many
SELECT
    id, product_id, favorite_list_id, created_at, updated_at
FROM
    favorite_products
WHERE
    favorite_list_id IN (/*SLICE:list_ids*/?)
ORDER BY
    rowid
`

func (q *Queries) GetProductsByListIDList(ctx context.Context, listIds []string) ([]FavoriteProduct, error) {
	query := getProductsByListIDList
	var queryParams []interface{}
	if len(listIds) > 0 {
		for _, v := range listIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:list_ids*/?", strings.Repeat(",?", len(listIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:list_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteProduct
	for rows.Next() {
		var i FavoriteProduct
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.FavoriteListID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertList = `-- name: InsertList :exec
INSERT INTO
    favorite_lists(id, list_type, created_at, updated_at)
VALUES
    (?, ?, ?, ?)
`

type InsertListParams struct {
	ID        string
	ListType  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertList(ctx context.Context, arg InsertListParams) error {
	_, err := q.db.ExecContext(ctx, insertList,
		arg.ID,
		arg.ListType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO
    favorite_members(
        id,
        user_id,
        favorite_list_id,
        created_at,
        updated_at,
        member_type
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertMemberParams struct {
	ID             string
	UserID         string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MemberType     int64
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember,
		arg.ID,
		arg.UserID,
		arg.FavoriteListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MemberType,
	)
	return err
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO
    favorite_products(
        id,
        product_id,
        favorite_list_id,
        created_at,
        updated_at
    )
VALUES
    (?, ?, ?, ?, ?) ON CONFLICT (product_id, favorite_list_id) DO
UPDATE
SET
    updated_at = excluded.updated_at
`

type InsertProductParams struct {
	ID             string
	ProductID      string
	FavoriteListID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Adding the same product twice must not duplicate the row; the collection is rewritten
// wholesale on every update, so the conflict can only come from a duplicate inside one batch.
func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.ExecContext(ctx, insertProduct,
		arg.ID,
		arg.ProductID,
		arg.FavoriteListID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateList = `-- name: UpdateList :exec
UPDATE
    favorite_lists
SET
    list_type = ?,
    created_at = ?,
    updated_at = ?
WHERE
    id = ?
`

type UpdateListParams struct {
	ListType  int64
	CreatedAt time.Time
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) error {
	_, err := q.db.ExecContext(ctx, updateList,
		arg.ListType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
