// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initFavoriteLists = `-- name: InitFavoriteLists :exec
CREATE TABLE IF NOT EXISTS favorite_lists (
    id text NOT NULL,
    list_type integer NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    PRIMARY KEY (id)
)
`

// Reproduces GORM's AutoMigrate output column for column so that CREATE TABLE IF NOT EXISTS is
// a no-op against deployed files; see internal/backend/functest/testdata/schema.sql.
func (q *Queries) InitFavoriteLists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteLists)
	return err
}

const initFavoriteMembers = `-- name: InitFavoriteMembers :exec
CREATE TABLE IF NOT EXISTS favorite_members (
    id text NOT NULL,
    user_id text NOT NULL,
    favorite_list_id text NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    member_type integer NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_favorite_lists_members FOREIGN KEY (favorite_list_id) REFERENCES favorite_lists(id),
    CONSTRAINT fk_favorite_members_user FOREIGN KEY (user_id) REFERENCES users(id)
)
`

func (q *Queries) InitFavoriteMembers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteMembers)
	return err
}

const initFavoriteProducts = `-- name: InitFavoriteProducts :exec
CREATE TABLE IF NOT EXISTS favorite_products (
    id text NOT NULL,
    product_id text NOT NULL,
    favorite_list_id text NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_favorite_lists_products FOREIGN KEY (favorite_list_id) REFERENCES favorite_lists(id),
    CONSTRAINT fk_favorite_products_product FOREIGN KEY (product_id) REFERENCES products(id)
)
`

func (q *Queries) InitFavoriteProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteProducts)
	return err
}
