// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initFavoriteLists = `-- name: InitFavoriteLists :exec
CREATE TABLE IF NOT EXISTS favorite_lists (
    id varchar(36) PRIMARY KEY,
    list_type int NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL
)
`

func (q *Queries) InitFavoriteLists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteLists)
	return err
}

const initFavoriteMembers = `-- name: InitFavoriteMembers :exec
CREATE TABLE IF NOT EXISTS favorite_members (
    id varchar(36) PRIMARY KEY,
    user_id varchar(36) NOT NULL,
    favorite_list_id varchar(36) NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    member_type int NOT NULL
)
`

func (q *Queries) InitFavoriteMembers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteMembers)
	return err
}

const initFavoriteProducts = `-- name: InitFavoriteProducts :exec
CREATE TABLE IF NOT EXISTS favorite_products (
    id varchar(36) PRIMARY KEY,
    product_id varchar(36) NOT NULL,
    favorite_list_id varchar(36) NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    UNIQUE KEY idx_unique_product (product_id, favorite_list_id)
)
`

func (q *Queries) InitFavoriteProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initFavoriteProducts)
	return err
}
