// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"database/sql"
	"time"
)

type Product struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	CategoryID sql.NullString
}

type ProductCategory struct {
	ID   string
	Name string
}

type ProductForm struct {
	ID        string
	ProductID string
	Name      string
}
