// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteFormsByProductID = `-- name: DeleteFormsByProductID :exec
DELETE FROM
    product_forms
WHERE
    product_id = ?
`

func (q *Queries) DeleteFormsByProductID(ctx context.Context, productID string) error {
	_, err := q.db.ExecContext(ctx, deleteFormsByProductID, productID)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    id, created_at, updated_at, name, category_id
FROM
    products
`

// GetAllProducts backs the empty-filter case of GetByListID. GORM's Find(&entities, uuids)
// treated an empty id slice as "no condition" and returned the whole table; that behaviour is
// pinned by TestProductIDListWithNoIDs_CurrentBehaviour.
func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByIDList = `-- name: GetCategoriesByIDList :many
SELECT
    id, name
FROM
    product_categories
WHERE
    id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetCategoriesByIDList(ctx context.Context, ids []string) ([]ProductCategory, error) {
	query := getCategoriesByIDList
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT
    id, name
FROM
    product_categories
WHERE
    name = ?
ORDER BY
    id
LIMIT
    1
`

// GORM's First() ordered by primary key, so a duplicated category name always resolved to the
// lowest id. The legacy dump contains two rows named ”, which is where that matters.
func (q *Queries) GetCategoryByName(ctx context.Context, name string) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i ProductCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getFormsByProductIDList = `-- name: GetFormsByProductIDList :many
SELECT
    product_id, id, name
FROM
    product_forms
WHERE
    product_id IN (/*SLICE:product_ids*/?)
ORDER BY
    rowid
`

func (q *Queries) GetFormsByProductIDList(ctx context.Context, productIds []string) ([]ProductForm, error) {
	query := getFormsByProductIDList
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductForm
	for rows.Next() {
		var i ProductForm
		if err := rows.Scan(&i.ProductID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id, created_at, updated_at, name, category_id
FROM
    products
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.CategoryID,
	)
	return i, err
}

const getProductsByIDList = `-- name: GetProductsByIDList :many
SELECT
    id, created_at, updated_at, name, category_id
FROM
    products
WHERE
    id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetProductsByIDList(ctx context.Context, ids []string) ([]Product, error) {
	query := getProductsByIDList
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO
    product_categories(id, name)
VALUES
    (?, ?)
`

type InsertCategoryParams struct {
	ID   string
	Name string
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertCategory, arg.ID, arg.Name)
	return err
}

const insertForm = `-- name: InsertForm :exec
INSERT INTO
    product_forms(product_id, id, name)
VALUES
    (?, ?, ?)
`

type InsertFormParams struct {
	ProductID string
	ID        string
	Name      string
}

func (q *Queries) InsertForm(ctx context.Context, arg InsertFormParams) error {
	_, err := q.db.ExecContext(ctx, insertForm, arg.ProductID, arg.ID, arg.Name)
	return err
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO
    products(id, created_at, updated_at, name, category_id)
VALUES
    (?, ?, ?, ?, ?)
`

type InsertProductParams struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	CategoryID sql.NullString
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.ExecContext(ctx, insertProduct,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.CategoryID,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE
    products
SET
    created_at = ?,
    updated_at = ?,
    name = ?,
    category_id = ?
WHERE
    id = ?
`

type UpdateProductParams struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	CategoryID sql.NullString
	ID         string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.CategoryID,
		arg.ID,
	)
	return err
}
