// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initProductCategories = `-- name: InitProductCategories :exec
CREATE TABLE IF NOT EXISTS product_categories (
    id varchar(255) PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
)
`

func (q *Queries) InitProductCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductCategories)
	return err
}

const initProductForms = `-- name: InitProductForms :exec
CREATE TABLE IF NOT EXISTS product_forms (
    id varchar(36) PRIMARY KEY,
    product_id varchar(36) NOT NULL,
    name varchar(255) NOT NULL
)
`

func (q *Queries) InitProductForms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductForms)
	return err
}

const initProducts = `-- name: InitProducts :exec
CREATE TABLE IF NOT EXISTS products (
    id varchar(36) PRIMARY KEY,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    name varchar(256) NOT NULL,
    category_id varchar(255)
)
`

func (q *Queries) InitProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProducts)
	return err
}
