// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initProductCategories = `-- name: InitProductCategories :exec
CREATE TABLE product_categories (
    id varchar(36) PRIMARY KEY,
    name varchar(255) NOT NULL
)
`

func (q *Queries) InitProductCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductCategories)
	return err
}

const initProductForms = `-- name: InitProductForms :exec
CREATE TABLE product_forms (
    product_id varchar(36) PRIMARY KEY,
    name varchar(255) NOT NULL,
    FOREIGN KEY (productId) REFERENCES products(id)
)
`

func (q *Queries) InitProductForms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductForms)
	return err
}

const initProducts = `-- name: InitProducts :exec
CREATE TABLE products (
    id varchar(36) PRIMARY KEY,
    name varchar(255) NOT NULL,
    category_id varchar(36),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
)
`

func (q *Queries) InitProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProducts)
	return err
}
