version: "2"
sql:
  - engine: "mysql"
    queries:
      - "query.sql"
      - "schema.sql"
    schema:
      - "schema.sql"
    gen:
      go:
        sql_package: "database/sql"
        sql_driver: "github.com/go-sql-driver/mysql"
        output_batch_file_name: batch.go
        output_db_file_name: db.go
        output_models_file_name: models.go
        output_querier_file_name: querier.go
        package: "sqlgen"
        out: "sqlgen"
