// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"database/sql"
	"time"
)

type Product struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	CategoryID sql.NullString
}

type ProductCategory struct {
	ID   string
	Name string
}

type ProductForm struct {
	ID        string
	ProductID string
	Name      string
}

type ProductList struct {
	ID        string
	Status    int32
	UpdatedAt time.Time
	CreatedAt time.Time
	Title     string
}

type ProductListMember struct {
	ID         string
	UserID     string
	ListID     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MemberType int32
}

type ProductListState struct {
	ID                   string
	ProductID            string
	ListID               string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Index                int32
	Count                sql.NullInt32
	FormIdx              sql.NullInt32
	Status               int32
	ReplacementCount     sql.NullInt32
	ReplacementFormIdx   sql.NullInt32
	ReplacementProductID sql.NullString
}

type User struct {
	ID    string
	Role  int32
	Login string
	Hash  string
}
