// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"database/sql"
	"time"
)

type ProductList struct {
	ID        string
	Status    int64
	UpdatedAt time.Time
	CreatedAt time.Time
	Title     string
}

type ProductListMember struct {
	ID         string
	UserID     string
	ListID     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MemberType int64
}

type ProductListState struct {
	ID                   string
	ProductID            string
	ListID               string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Index                int64
	Count                sql.NullInt64
	FormIdx              sql.NullInt64
	Status               int64
	ReplacementCount     sql.NullInt64
	ReplacementFormIdx   sql.NullInt64
	ReplacementProductID sql.NullString
}
