// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteList = `-- name: DeleteList :exec
DELETE FROM
    product_lists
WHERE
    id = ?
`

func (q *Queries) DeleteList(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteList, id)
	return err
}

const deleteMembersByListID = `-- name: DeleteMembersByListID :exec
DELETE FROM
    product_list_members
WHERE
    list_id = ?
`

func (q *Queries) DeleteMembersByListID(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, deleteMembersByListID, listID)
	return err
}

const deleteStatesByListID = `-- name: DeleteStatesByListID :exec
DELETE FROM
    product_list_states
WHERE
    list_id = ?
`

func (q *Queries) DeleteStatesByListID(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, deleteStatesByListID, listID)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT
    id, status, updated_at, created_at, title
FROM
    product_lists
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetListByID(ctx context.Context, id string) (ProductList, error) {
	row := q.db.QueryRowContext(ctx, getListByID, id)
	var i ProductList
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Title,
	)
	return i, err
}

const getListIDListByUserID = `-- name: GetListIDListByUserID :many
SELECT
    list_id
FROM
    product_list_members
WHERE
    user_id = ?
`

func (q *Queries) GetListIDListByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getListIDListByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var list_id string
		if err := rows.Scan(&list_id); err != nil {
			return nil, err
		}
		items = append(items, list_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByIDList = `-- name: GetListsByIDList :many
SELECT
    id, status, updated_at, created_at, title
FROM
    product_lists
WHERE
    id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetListsByIDList(ctx context.Context, ids []string) ([]ProductList, error) {
	query := getListsByIDList
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductList
	for rows.Next() {
		var i ProductList
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersByListIDList = `-- name: GetMembersByListIDList :many
SELECT
    id, user_id, list_id, created_at, updated_at, member_type
FROM
    product_list_members
WHERE
    list_id IN (/*SLICE:list_ids*/?)
ORDER BY
    rowid
`

func (q *Queries) GetMembersByListIDList(ctx context.Context, listIds []string) ([]ProductListMember, error) {
	query := getMembersByListIDList
	var queryParams []interface{}
	if len(listIds) > 0 {
		for _, v := range listIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:list_ids*/?", strings.Repeat(",?", len(listIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:list_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductListMember
	for rows.Next() {
		var i ProductListMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatesByListIDList = `-- name: GetStatesByListIDList :many
SELECT
    id, product_id, list_id, created_at, updated_at, "index", count, form_idx, status, replacement_count, replacement_form_idx, replacement_product_id
FROM
    product_list_states
WHERE
    list_id IN (/*SLICE:list_ids*/?)
ORDER BY
    rowid
`

func (q *Queries) GetStatesByListIDList(ctx context.Context, listIds []string) ([]ProductListState, error) {
	query := getStatesByListIDList
	var queryParams []interface{}
	if len(listIds) > 0 {
		for _, v := range listIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:list_ids*/?", strings.Repeat(",?", len(listIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:list_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductListState
	for rows.Next() {
		var i ProductListState
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ListID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Index,
			&i.Count,
			&i.FormIdx,
			&i.Status,
			&i.ReplacementCount,
			&i.ReplacementFormIdx,
			&i.ReplacementProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertList = `-- name: InsertList :exec
INSERT INTO
    product_lists(id, status, updated_at, created_at, title)
VALUES
    (?, ?, ?, ?, ?)
`

type InsertListParams struct {
	ID        string
	Status    int64
	UpdatedAt time.Time
	CreatedAt time.Time
	Title     string
}

func (q *Queries) InsertList(ctx context.Context, arg InsertListParams) error {
	_, err := q.db.ExecContext(ctx, insertList,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.CreatedAt,
		arg.Title,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO
    product_list_members(
        id,
        user_id,
        list_id,
        created_at,
        updated_at,
        member_type
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertMemberParams struct {
	ID         string
	UserID     string
	ListID     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MemberType int64
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember,
		arg.ID,
		arg.UserID,
		arg.ListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MemberType,
	)
	return err
}

const insertState = `-- name: InsertState :exec
INSERT INTO
    product_list_states(
        id,
        product_id,
        list_id,
        created_at,
        updated_at,
        "index",
        count,
        form_idx,
        status,
        replacement_count,
        replacement_form_idx,
        replacement_product_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStateParams struct {
	ID                   string
	ProductID            string
	ListID               string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Index                int64
	Count                sql.NullInt64
	FormIdx              sql.NullInt64
	Status               int64
	ReplacementCount     sql.NullInt64
	ReplacementFormIdx   sql.NullInt64
	ReplacementProductID sql.NullString
}

func (q *Queries) InsertState(ctx context.Context, arg InsertStateParams) error {
	_, err := q.db.ExecContext(ctx, insertState,
		arg.ID,
		arg.ProductID,
		arg.ListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Index,
		arg.Count,
		arg.FormIdx,
		arg.Status,
		arg.ReplacementCount,
		arg.ReplacementFormIdx,
		arg.ReplacementProductID,
	)
	return err
}

const updateList = `-- name: UpdateList :exec
UPDATE
    product_lists
SET
    status = ?,
    updated_at = ?,
    created_at = ?,
    title = ?
WHERE
    id = ?
`

type UpdateListParams struct {
	Status    int64
	UpdatedAt time.Time
	CreatedAt time.Time
	Title     string
	ID        string
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) error {
	_, err := q.db.ExecContext(ctx, updateList,
		arg.Status,
		arg.UpdatedAt,
		arg.CreatedAt,
		arg.Title,
		arg.ID,
	)
	return err
}
