// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteProductListByID = `-- name: DeleteProductListByID :exec
DELETE FROM
    product_lists
WHERE
    id = ?
`

func (q *Queries) DeleteProductListByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProductListByID, id)
	return err
}

const deleteProductListMembersByListID = `-- name: DeleteProductListMembersByListID :exec
DELETE FROM
    product_list_members
WHERE
    list_id = ?
`

func (q *Queries) DeleteProductListMembersByListID(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, deleteProductListMembersByListID, listID)
	return err
}

const deleteProductListStatesByListID = `-- name: DeleteProductListStatesByListID :exec
DELETE FROM
    product_list_states
WHERE
    list_id = ?
`

func (q *Queries) DeleteProductListStatesByListID(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, deleteProductListStatesByListID, listID)
	return err
}

const getMembersByListID = `-- name: GetMembersByListID :many
SELECT
    m.user_id,
    m.member_type,
    m.created_at,
    m.updated_at,
    COALESCE(u.login, '') AS login
FROM
    product_list_members m
    LEFT JOIN users u ON u.id = m.user_id
WHERE
    m.list_id = ?
`

type GetMembersByListIDRow struct {
	UserID     string
	MemberType int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Login      string
}

func (q *Queries) GetMembersByListID(ctx context.Context, listID string) ([]GetMembersByListIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByListIDRow
	for rows.Next() {
		var i GetMembersByListIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.MemberType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Login,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductListByID = `-- name: GetProductListByID :one
SELECT
    id,
    status,
    updated_at,
    created_at,
    title
FROM
    product_lists
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetProductListByID(ctx context.Context, id string) (ProductList, error) {
	row := q.db.QueryRowContext(ctx, getProductListByID, id)
	var i ProductList
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Title,
	)
	return i, err
}

const getProductListIDsByUserID = `-- name: GetProductListIDsByUserID :many
SELECT
    list_id
FROM
    product_list_members
WHERE
    user_id = ?
`

func (q *Queries) GetProductListIDsByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProductListIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var list_id string
		if err := rows.Scan(&list_id); err != nil {
			return nil, err
		}
		items = append(items, list_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatesByListID = `-- name: GetStatesByListID :many
SELECT
    product_id,
    created_at,
    updated_at,
    ` + "`" + `index` + "`" + `,
    count,
    form_idx,
    status,
    replacement_count,
    replacement_form_idx,
    replacement_product_id
FROM
    product_list_states
WHERE
    list_id = ?
`

type GetStatesByListIDRow struct {
	ProductID            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Index                int32
	Count                sql.NullInt32
	FormIdx              sql.NullInt32
	Status               int32
	ReplacementCount     sql.NullInt32
	ReplacementFormIdx   sql.NullInt32
	ReplacementProductID sql.NullString
}

func (q *Queries) GetStatesByListID(ctx context.Context, listID string) ([]GetStatesByListIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatesByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatesByListIDRow
	for rows.Next() {
		var i GetStatesByListIDRow
		if err := rows.Scan(
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Index,
			&i.Count,
			&i.FormIdx,
			&i.Status,
			&i.ReplacementCount,
			&i.ReplacementFormIdx,
			&i.ReplacementProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProductListMember = `-- name: InsertProductListMember :exec
INSERT INTO
    product_list_members(id, user_id, list_id, created_at, updated_at, member_type)
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertProductListMemberParams struct {
	ID         string
	UserID     string
	ListID     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MemberType int32
}

func (q *Queries) InsertProductListMember(ctx context.Context, arg InsertProductListMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertProductListMember,
		arg.ID,
		arg.UserID,
		arg.ListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MemberType,
	)
	return err
}

const insertProductListState = `-- name: InsertProductListState :exec
INSERT INTO
    product_list_states(
        id,
        product_id,
        list_id,
        created_at,
        updated_at,
        ` + "`" + `index` + "`" + `,
        count,
        form_idx,
        status,
        replacement_count,
        replacement_form_idx,
        replacement_product_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProductListStateParams struct {
	ID                   string
	ProductID            string
	ListID               string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Index                int32
	Count                sql.NullInt32
	FormIdx              sql.NullInt32
	Status               int32
	ReplacementCount     sql.NullInt32
	ReplacementFormIdx   sql.NullInt32
	ReplacementProductID sql.NullString
}

func (q *Queries) InsertProductListState(ctx context.Context, arg InsertProductListStateParams) error {
	_, err := q.db.ExecContext(ctx, insertProductListState,
		arg.ID,
		arg.ProductID,
		arg.ListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Index,
		arg.Count,
		arg.FormIdx,
		arg.Status,
		arg.ReplacementCount,
		arg.ReplacementFormIdx,
		arg.ReplacementProductID,
	)
	return err
}

const loadProductsByIDs = `-- name: LoadProductsByIDs :many
SELECT
    p.id,
    p.created_at,
    p.updated_at,
    p.name,
    p.category_id,
    pc.name AS category_name,
    pf.id AS form_id,
    pf.name AS form_name
FROM
    products p
    LEFT JOIN product_categories pc ON p.category_id = pc.id OR p.category_id = pc.name
    LEFT JOIN product_forms pf ON pf.product_id = p.id
WHERE
    p.id IN (/*SLICE:product_ids*/?)
`

type LoadProductsByIDsRow struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	CategoryID   sql.NullString
	CategoryName sql.NullString
	FormID       sql.NullString
	FormName     sql.NullString
}

func (q *Queries) LoadProductsByIDs(ctx context.Context, productIds []string) ([]LoadProductsByIDsRow, error) {
	query := loadProductsByIDs
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadProductsByIDsRow
	for rows.Next() {
		var i LoadProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.FormID,
			&i.FormName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStateIndexByProductID = `-- name: UpdateStateIndexByProductID :exec
UPDATE product_list_states
SET
    ` + "`" + `index` + "`" + ` = ?
WHERE
    list_id = ?
    AND product_id = ?
`

type UpdateStateIndexByProductIDParams struct {
	Index     int32
	ListID    string
	ProductID string
}

func (q *Queries) UpdateStateIndexByProductID(ctx context.Context, arg UpdateStateIndexByProductIDParams) error {
	_, err := q.db.ExecContext(ctx, updateStateIndexByProductID, arg.Index, arg.ListID, arg.ProductID)
	return err
}

const upsertProductList = `-- name: UpsertProductList :exec
INSERT INTO
    product_lists(id, status, updated_at, created_at, title)
VALUES
    (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    status = VALUES(status),
    updated_at = VALUES(updated_at),
    created_at = VALUES(created_at),
    title = VALUES(title)
`

type UpsertProductListParams struct {
	ID        string
	Status    int32
	UpdatedAt time.Time
	CreatedAt time.Time
	Title     string
}

func (q *Queries) UpsertProductList(ctx context.Context, arg UpsertProductListParams) error {
	_, err := q.db.ExecContext(ctx, upsertProductList,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.CreatedAt,
		arg.Title,
	)
	return err
}
