// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package sqlgen

import (
	"context"
)

const initProductListMembers = `-- name: InitProductListMembers :exec
CREATE TABLE IF NOT EXISTS product_list_members (
    id varchar(36) PRIMARY KEY,
    user_id varchar(36) NOT NULL,
    list_id varchar(36) NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    member_type int NOT NULL,
    UNIQUE KEY idx_list_user (user_id, list_id)
)
`

func (q *Queries) InitProductListMembers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductListMembers)
	return err
}

const initProductListStates = `-- name: InitProductListStates :exec
CREATE TABLE IF NOT EXISTS product_list_states (
    id varchar(36) PRIMARY KEY,
    product_id varchar(36) NOT NULL,
    list_id varchar(36) NOT NULL,
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    ` + "`" + `index` + "`" + ` int NOT NULL,
    count int,
    form_idx int,
    status int NOT NULL,
    replacement_count int,
    replacement_form_idx int,
    replacement_product_id varchar(36)
)
`

func (q *Queries) InitProductListStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductListStates)
	return err
}

const initProductLists = `-- name: InitProductLists :exec
CREATE TABLE IF NOT EXISTS product_lists (
    id varchar(36) PRIMARY KEY,
    status int NOT NULL,
    updated_at datetime NOT NULL,
    created_at datetime NOT NULL,
    title varchar(255) NOT NULL
)
`

func (q *Queries) InitProductLists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initProductLists)
	return err
}
