// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package sqlgen

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForInsertCategories uint32 = 1

func convertRowsForInsertCategories(w *io.PipeWriter, arg []InsertCategoriesParams) {
	e := mysqltsv.NewEncoder(w, 3, nil)
	for _, row := range arg {
		e.AppendString(row.MapID)
		e.AppendValue(row.Number)
		e.AppendString(row.Category)
	}
	w.CloseWithError(e.Close())
}

// InsertCategories uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) InsertCategories(ctx context.Context, arg []InsertCategoriesParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("InsertCategories_%d", atomic.AddUint32(&readerHandlerSequenceForInsertCategories, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForInsertCategories(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `shop_map_categories` %s (map_id, number, category)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

var readerHandlerSequenceForInsertViewers uint32 = 1

func convertRowsForInsertViewers(w *io.PipeWriter, arg []InsertViewersParams) {
	e := mysqltsv.NewEncoder(w, 2, nil)
	for _, row := range arg {
		e.AppendString(row.MapID)
		e.AppendString(row.UserID)
	}
	w.CloseWithError(e.Close())
}

// InsertViewers uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) InsertViewers(ctx context.Context, arg []InsertViewersParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("InsertViewers_%d", atomic.AddUint32(&readerHandlerSequenceForInsertViewers, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForInsertViewers(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `shop_map_viewers` %s (map_id, user_id)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
