// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlgen

import (
	"time"
)

type ShopMap struct {
	ID        string
	OwnerID   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ShopMapCategory struct {
	MapID    string
	Category string
}

type ShopMapViewer struct {
	MapID  string
	UserID string
}
