// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login with existing user",
                "operationId": "auth-login",
                "parameters": [
                    {
                        "description": "creds",
                        "name": "opts",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Credentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TokenResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logout from session",
                "operationId": "auth-logout",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "refresh access token",
                "operationId": "auth-refresh",
                "parameters": [
                    {
                        "description": "refresh token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TokenResponse"
                        }
                    }
                }
            }
        },
        "/favorite/id/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "get list of favorite products by id",
                "operationId": "get-favorite-list-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of favorites list",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/favorite/id/{id}/product": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "add new products to list of favorties",
                "operationId": "add-favorite-products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of favorites list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ids of new products",
                        "name": "products",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ProductList"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "remove some products from favorite list",
                "operationId": "remove-favorite-products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of favorites list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ids of new products",
                        "name": "products",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ProductList"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/favorite/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "get all favorites lists, related to logged user",
                "operationId": "get-user-favorites-lists",
                "responses": {}
            }
        },
        "/lists": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "get product lists by user id",
                "operationId": "product-list-get",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "creates new product list",
                "operationId": "product-list-create",
                "parameters": [
                    {
                        "description": "options of new product list",
                        "name": "opts",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/list.ListOptions"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/lists/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "get product list by list id",
                "operationId": "product-list-get-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of product list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "update product list by id",
                "operationId": "product-list-update-by-id",
                "parameters": [
                    {
                        "description": "opts to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/list.ListOptions"
                        }
                    },
                    {
                        "type": "string",
                        "description": "id of product list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "delete product list by id",
                "operationId": "product-list-delete-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of product list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/lists/{id}/members": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "add viewers to product list",
                "operationId": "product-list-add-members",
                "parameters": [
                    {
                        "description": "users to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/list.MemberOptions"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "id of product list",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "delete members from product list",
                "operationId": "product-list-delete-members",
                "parameters": [
                    {
                        "description": "id of members to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "product list id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/lists/{id}/products": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "add new products to product list",
                "operationId": "product-list-add-products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product list id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "new products",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/api.ProductStateOptions"
                            }
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "delete products from product list",
                "operationId": "product-list-delete-products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product list id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ids of deleting products",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/lists/{id}/products/{product_id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "update single product state in given product list",
                "operationId": "product-list-update-state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product list id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "product state product id",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "product state options",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ProductStateOptions"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/lists/{id}/reorder": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "ProductList"
                ],
                "summary": "change order of products in product list",
                "operationId": "product-list-reorder-states",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product list id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ids of products in new order",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/product": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Creates new product",
                "operationId": "product-create",
                "parameters": [
                    {
                        "description": "product to create",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/product.Options"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/product/id/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get product info",
                "operationId": "product-get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Update existing new product",
                "operationId": "product-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "product id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "product to update",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/product.Options"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/product/list/{ids}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get products info",
                "operationId": "product-get-list",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "product id",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/shopmap": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "Creates new shop map",
                "operationId": "shopmap-create",
                "parameters": [
                    {
                        "description": "shop map to create",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopmap.Options"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/shopmap/id/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "Get existing shop map by it's ID",
                "operationId": "shopmap-get-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of shop map",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "fully updates shop map",
                "operationId": "shopmap-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of shop map",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "new configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shopmap.Options"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "Deletes shop map",
                "operationId": "shopmap-delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of shop map",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/shopmap/id/{id}/reorder": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "only reorder categories in given shop map",
                "operationId": "shopmap-reorder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of shop map",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "new order of categories",
                        "name": "categories",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/shopmap/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShopMap"
                ],
                "summary": "Get shop maps of current logged user",
                "operationId": "shopmap-get-current-user",
                "responses": {}
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "list all users",
                "operationId": "user-get-all",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "creates new user",
                "operationId": "user-register",
                "parameters": [
                    {
                        "description": "data for creating new user",
                        "name": "opts",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateOptions"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.ProductList": {
            "type": "object",
            "properties": {
                "product_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ProductStateOptions": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "form_idx": {
                    "type": "integer"
                },
                "replacement": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer"
                        },
                        "form_idx": {
                            "type": "integer"
                        },
                        "product_id": {
                            "type": "integer"
                        }
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "api.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "auth.Credentials": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "list.ListOptions": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "list.MemberOptions": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "product.Options": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "forms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "shopmap.Options": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                },
                "viewers_id": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "user.CreateOptions": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Auth",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ShoPlanner",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
