basePath: /api/v1
definitions:
  api.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  api.TokenResponse:
    properties:
      access_token:
        type: string
      expires:
        type: string
      refresh_token:
        type: string
      type:
        type: string
    type: object
  auth.Credentials:
    properties:
      device_id:
        type: string
      login:
        type: string
      password:
        type: string
    type: object
  product.Options:
    properties:
      category:
        type: string
      forms:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  shopmap.Options:
    properties:
      categories:
        items:
          type: string
        type: array
        uniqueItems: true
      viewers_id:
        items:
          type: string
        type: array
        uniqueItems: true
    type: object
  user.CreateOptions:
    properties:
      login:
        type: string
      password:
        maxLength: 72
        type: string
    required:
    - password
    type: object
info:
  contact: {}
  title: ShoPlanner
  version: 0.0.1
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      operationId: auth-login
      parameters:
      - description: creds
        in: body
        name: opts
        required: true
        schema:
          $ref: '#/definitions/auth.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TokenResponse'
      summary: login with existing user
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      operationId: auth-logout
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: logout from session
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      operationId: auth-refresh
      parameters:
      - description: refresh token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/api.RefreshRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TokenResponse'
      summary: refresh access token
      tags:
      - Auth
  /product:
    post:
      consumes:
      - application/json
      operationId: product-create
      parameters:
      - description: product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.Options'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Creates new product
      tags:
      - Product
  /product/id/{id}:
    get:
      consumes:
      - application/json
      operationId: product-get
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get product info
      tags:
      - Product
    put:
      operationId: product-update
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      - description: product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.Options'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Update existing new product
      tags:
      - Product
  /product/list/{ids}:
    get:
      consumes:
      - application/json
      operationId: product-get-list
      parameters:
      - collectionFormat: csv
        description: product id
        in: path
        items:
          type: string
        name: ids
        required: true
        type: array
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get products info
      tags:
      - Product
  /shopmap:
    post:
      consumes:
      - application/json
      operationId: shopmap-create
      parameters:
      - description: shop map to create
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/shopmap.Options'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Creates new shop map
      tags:
      - ShopMap
  /shopmap/id/{id}:
    delete:
      operationId: shopmap-delete
      parameters:
      - description: id of shop map
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Deletes shop map
      tags:
      - ShopMap
    get:
      operationId: shopmap-get-id
      parameters:
      - description: id of shop map
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get existing shop map by it's ID
      tags:
      - ShopMap
    put:
      consumes:
      - application/json
      operationId: shopmap-update
      parameters:
      - description: id of shop map
        in: query
        name: id
        required: true
        type: string
      - description: new configuration
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/shopmap.Options'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: fully updates shop map
      tags:
      - ShopMap
  /shopmap/id/{id}/reorder:
    patch:
      consumes:
      - application/json
      operationId: shopmap-reorder
      parameters:
      - description: id of shop map
        in: query
        name: id
        required: true
        type: string
      - description: new order of categories
        in: body
        name: categories
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: only reorder categories in given shop map
      tags:
      - ShopMap
  /shopmap/user:
    get:
      operationId: shopmap-get-current-user
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get shop maps of current logged user
      tags:
      - ShopMap
  /user:
    get:
      operationId: user-get-all
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: list all users
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      operationId: user-register
      parameters:
      - description: data for creating new user
        in: body
        name: opts
        required: true
        schema:
          $ref: '#/definitions/user.CreateOptions'
      produces:
      - application/json
      responses: {}
      summary: creates new user
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Auth
    type: apiKey
swagger: "2.0"
